# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d11f9fa69f691057ca9edc66df5e10b6bf4874e3f5270b1f78eb1230a1d2b3be64a1410a9d9012ef29237581fcea3e4c17f0005de862e6608697c25b746175

test:
  secret_key_base: dc7f21b33467cd8fa0e52d187931d5f1da1630576e6ca827841bbdf077f35f4032b5745d1be21c6cf5c8decb81d6756415cbd5fa21a01c42188232205234fadd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
